### ISSUE TITLE
Find a better way to handle the top margin on `/#section-id` navigation

### ISSUE THREAD

**Issue by filiptrivan** [filiptrivan/spiderly-website#41]
### Current Behavior:
To offset the header when navigating to anchored sections, we currently use this CSS:
```css
.section {
  padding-top: 80px;
  margin-top: -80px;
}
```

### Problem:
While this visually works, it introduces a text selection issue, users can't copy text at the top of a section easily because of the negative margin.

### Attempted Fix (Did Not Work):
We tried using native scroll margin:
```css
[id] {
    scroll-margin-top: 80px;
}
```
